name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: 'true'
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: signing key
      run: echo ${{ secrets.SNKEY }} | base64 -d > key.snk

    - name: Build
      run: dotnet build --configuration Release -p:SignAssembly=True --no-restore
    - name: Test
      run: |
        dotnet test --no-build --no-restore --configuration Release

    - name: Make packages
      run: |
        dotnet pack --no-build --no-restore --configuration Release -p:SignAssembly=True --output ./artifacts/ src/Pdsr.Core
        dotnet pack --no-build --no-restore --configuration Release -p:SignAssembly=True --output ./artifacts/ src/Pdsr.Core.Extensions
        dotnet pack --no-build --no-restore --configuration Release -p:SignAssembly=True --output ./artifacts/ src/Pdsr.Data
        dotnet pack --no-build --no-restore --configuration Release -p:SignAssembly=True --output ./artifacts/ src/Pdsr.Hosting


    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: |
          **/*.nupkg
          **/*.snupkg
    - name: Publish packages
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}

